---
tags:
- metaprogramacion
- objetos
- delegator
- method_missing
layout: input_bottom
editor: code
type: problem
extra_visible: false
language: 
teacher_info: ''
manual_evaluation: false
choices: []
